In [24]:
from Datasetmain import CrystalProcess,CrystalProcess_init
import argparse

class CrystalProcess_test(argparse.Namespace):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.root_samp = './for-gnn-contcar'  # structure files
        self.root_y = './label_csv' # csv files
        self.y_name = 'core_state'
        self.save = True
        self.cover = True
        self.outputdir = 'F:\\OnlinePacket\\programfiles\\Python\\TangerGNN\\Transform_rebuild\\TGNN\\PTs\\crystal'
        self.ptname = 'Crystall_dataset.pt'
        self.seed = 20
        self.num_jobs = 1
        self.divid = False
        self.maxnodes = 200
        self.maxAttempts = 100
        self.length = 'all'
        self.begin = 1
        self.y_norm = False
        self.y_norm_range = [0,1000]

args = CrystalProcess_test()


nn_params = {
    'root_samp': args.root_samp,
    'root_y': args.root_y,
    'y_name': args.y_name,
    'save': args.save,
    'cover': args.cover,
    'outputdir': args.outputdir,
    'ptname': args.ptname,
    'seed': args.seed,
    'num_jobs': args.num_jobs,
    'divid': args.divid,
    'maxnodes': args.maxnodes,
    'maxAttempts': args.maxAttempts,
    'length': args.length,
    'begin': args.begin,
    'y_norm': args.y_norm,
    'y_norm_range': args.y_norm_range,
}

dataset1 = CrystalProcess(**nn_params)
print(dataset1[1])

beginning save all 1000 datas whit num_jobs=1F:\OnlinePacket\programfiles\Python\TangerGNN\Transform_rebuild\TGNN\PTs\crystal\Crystall_dataset.pt divid=False


cutting: 100%|██████████| 1/1 [00:00<00:00,  5.88it/s]


cutting finished whit the length of 1000
saved in  F:\OnlinePacket\programfiles\Python\TangerGNN\Transform_rebuild\TGNN\PTs\crystal\Crystall_dataset.pt
Data(x=[200, 1], edge_index=[2, 170], y=[200, 1], new_pos=[200, 4], y_mark=[200, 1], num_nodes=200, bond_length=[170, 1])


In [25]:
dataset1[999].y

tensor([[ 45.5421],
        [ 44.6875],
        [ 43.7242],
        [ 45.1825],
        [ 46.0462],
        [ 44.4844],
        [ 45.5479],
        [ 46.2598],
        [ 44.2579],
        [ 44.8719],
        [ 44.6194],
        [ 45.1893],
        [ 44.2933],
        [ 44.2343],
        [ 45.8907],
        [ 44.1585],
        [ 45.8436],
        [ 44.9968],
        [ 45.2444],
        [ 45.3739],
        [ 43.7746],
        [ 45.7689],
        [ 45.1970],
        [ 45.9675],
        [ 44.0465],
        [ 44.6858],
        [ 44.6105],
        [ 43.6874],
        [ 45.3389],
        [ 45.0527],
        [ 45.6102],
        [ 45.7559],
        [ 44.8959],
        [ 44.5754],
        [ 44.2666],
        [ 44.8225],
        [ 44.3167],
        [ 44.6092],
        [ 44.9939],
        [ 44.4380],
        [ 45.2195],
        [ 44.5141],
        [ 44.1992],
        [ 45.2434],
        [ 43.8976],
        [ 44.4483],
        [ 44.9159],
        [ 43.9691],
        [ 44.2488],
        [ 45.1824],


In [26]:
import torch
import os
path=os.path.join(args.outputdir,args.ptname)
dataset=torch.load(path)

In [27]:
dataset[0]

Data(x=[200, 1], edge_index=[2, 170], y=[200, 1], new_pos=[200, 4], y_mark=[200, 1], num_nodes=200, bond_length=[170, 1])

In [28]:
dataset[0].x

tensor([[ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 7],
        [ 7],
        [16],
        [16],
        [16],
        [16],
        [ 8],
        [ 8],
        [ 8],
        [ 8],
        [ 8],
        [ 8],
        [ 8],
        [ 8],
        [ 8],
      

In [29]:
dataset[0].edge_index

tensor([[ 56,  57,  57,  58,  58,  59,  59,  60,  60,  60,  61,  61,  61,  62,
          63,  64,  65,  67,  68,  69,  70,  72,  72,  73,  73,  74,  75,  76,
          77,  87,  97, 108, 115, 118, 123, 123, 123, 124, 124, 124, 125, 125,
         125, 125, 126, 126, 126, 126, 127, 127, 127, 127, 128, 128, 128, 128,
         129, 129, 129, 129, 130, 130, 130, 130, 131, 131, 132, 132, 132, 132,
         133, 133, 133, 133, 134, 134, 134, 135, 135, 135, 136, 136, 136, 137,
         137, 137, 138, 138, 138, 139, 139, 139, 140, 140, 140, 141, 141, 141,
         142, 142, 142, 143, 143, 143, 144, 144, 144, 145, 145, 145, 146, 146,
         147, 147, 148, 148, 148, 148, 149, 149, 150, 150, 151, 151, 152, 152,
         153, 153, 153, 153, 154, 154, 155, 155, 156, 157, 158, 159, 160, 161,
         162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175,
         178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
         193, 194],
        [ 59,  61,  58,  57, 136

In [30]:
dataset[0].y

tensor([[ 44.2891],
        [ 44.7083],
        [ 43.1984],
        [ 45.0348],
        [ 45.3521],
        [ 44.9961],
        [ 45.0971],
        [ 45.7224],
        [ 43.8729],
        [ 44.4819],
        [ 45.3362],
        [ 44.9009],
        [ 44.9458],
        [ 44.7558],
        [ 45.6299],
        [ 44.9737],
        [ 44.9918],
        [ 44.5497],
        [ 46.2324],
        [ 44.2867],
        [ 44.0016],
        [ 45.6379],
        [ 45.2641],
        [ 45.9256],
        [ 44.7027],
        [ 44.6349],
        [ 45.3209],
        [ 43.9328],
        [ 44.9332],
        [ 44.5431],
        [ 44.8005],
        [ 44.1240],
        [ 44.7944],
        [ 44.9301],
        [ 45.0839],
        [ 44.6929],
        [ 44.6851],
        [ 44.2914],
        [ 44.7979],
        [ 45.0421],
        [ 45.4579],
        [ 45.0772],
        [ 44.5559],
        [ 45.6000],
        [ 43.7453],
        [ 44.1436],
        [ 46.1334],
        [ 43.5089],
        [ 44.4260],
        [ 45.0203],


In [31]:
import torch
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])