In [9]:
from Datasetmain import CrystalProcess,CrystalProcess_init
import argparse

class CrystalProcess_test(argparse.Namespace):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.root_samp = './for-gnn-contcar'  # structure files
        self.root_y = './label_csv' # csv files
        self.y_name = 'core_state'
        self.save = True
        self.cover = True
        self.outputdir = 'F:\\OnlinePacket\\programfiles\\Python\\TangerGNN\\Transform_rebuild\\TGNN\\PTs\\crystal_norm_100'
        self.ptname = 'Crystall_dataset.pt'
        self.seed = 20
        self.num_jobs = 1
        self.divid = False
        self.maxnodes = 200
        self.maxAttempts = 100
        self.length = 'all'
        self.begin = 1
        self.y_norm = True
        self.y_norm_range = [0,100]

args = CrystalProcess_test()


nn_params = {
    'root_samp': args.root_samp,
    'root_y': args.root_y,
    'y_name': args.y_name,
    'save': args.save,
    'cover': args.cover,
    'outputdir': args.outputdir,
    'ptname': args.ptname,
    'seed': args.seed,
    'num_jobs': args.num_jobs,
    'divid': args.divid,
    'maxnodes': args.maxnodes,
    'maxAttempts': args.maxAttempts,
    'length': args.length,
    'begin': args.begin,
    'y_norm': args.y_norm,
    'y_norm_range': args.y_norm_range,
}

dataset1 = CrystalProcess(**nn_params)
print(dataset1[1])

cutting:   0%|          | 0/1 [00:00<?, ?it/s]

cutting finished whit the length of 1000


cutting: 100%|██████████| 1/1 [00:00<00:00,  3.82it/s]

saved in  F:\OnlinePacket\programfiles\Python\TangerGNN\Transform_rebuild\TGNN\PTs\crystal_norm_100\Crystall_dataset.pt
Data(x=[200, 1], edge_index=[2, 170], y=[200, 1], new_pos=[200, 4], y_mark=[200, 1], num_nodes=200, bond_length=[170, 1])


beginning save all 1000 datas whit num_jobs=1F:\OnlinePacket\programfiles\Python\TangerGNN\Transform_rebuild\TGNN\PTs\crystal_norm_100\Crystall_dataset.pt divid=False


cutting:   0%|          | 0/1 [00:00<?, ?it/s]

cutting finished whit the length of 1000


cutting: 100%|██████████| 1/1 [00:00<00:00,  4.52it/s]

saved in  F:\OnlinePacket\programfiles\Python\TangerGNN\Transform_rebuild\TGNN\PTs\crystal_norm_100\Crystall_dataset.pt
Data(x=[200, 1], edge_index=[2, 170], y=[200, 1], new_pos=[200, 4], y_mark=[200, 1], num_nodes=200, bond_length=[170, 1])


In [10]:
dataset1[999].y

tensor([[0.4554],
        [0.4469],
        [0.4372],
        [0.4518],
        [0.4605],
        [0.4448],
        [0.4555],
        [0.4626],
        [0.4426],
        [0.4487],
        [0.4462],
        [0.4519],
        [0.4429],
        [0.4423],
        [0.4589],
        [0.4416],
        [0.4584],
        [0.4500],
        [0.4524],
        [0.4537],
        [0.4377],
        [0.4577],
        [0.4520],
        [0.4597],
        [0.4405],
        [0.4469],
        [0.4461],
        [0.4369],
        [0.4534],
        [0.4505],
        [0.4561],
        [0.4576],
        [0.4490],
        [0.4458],
        [0.4427],
        [0.4482],
        [0.4432],
        [0.4461],
        [0.4499],
        [0.4444],
        [0.4522],
        [0.4451],
        [0.4420],
        [0.4524],
        [0.4390],
        [0.4445],
        [0.4492],
        [0.4397],
        [0.4425],
        [0.4518],
        [0.4492],
        [0.4552],
        [0.4567],
        [0.4526],
        [0.4379],
        [0

tensor([[0.4554],
        [0.4469],
        [0.4372],
        [0.4518],
        [0.4605],
        [0.4448],
        [0.4555],
        [0.4626],
        [0.4426],
        [0.4487],
        [0.4462],
        [0.4519],
        [0.4429],
        [0.4423],
        [0.4589],
        [0.4416],
        [0.4584],
        [0.4500],
        [0.4524],
        [0.4537],
        [0.4377],
        [0.4577],
        [0.4520],
        [0.4597],
        [0.4405],
        [0.4469],
        [0.4461],
        [0.4369],
        [0.4534],
        [0.4505],
        [0.4561],
        [0.4576],
        [0.4490],
        [0.4458],
        [0.4427],
        [0.4482],
        [0.4432],
        [0.4461],
        [0.4499],
        [0.4444],
        [0.4522],
        [0.4451],
        [0.4420],
        [0.4524],
        [0.4390],
        [0.4445],
        [0.4492],
        [0.4397],
        [0.4425],
        [0.4518],
        [0.4492],
        [0.4552],
        [0.4567],
        [0.4526],
        [0.4379],
        [0

In [11]:
import torch
import os
path=os.path.join(args.outputdir,args.ptname)
dataset=torch.load(path)

In [12]:
dataset[0]

Data(x=[200, 1], edge_index=[2, 170], y=[200, 1], new_pos=[200, 4], y_mark=[200, 1], num_nodes=200, bond_length=[170, 1])

Data(x=[200, 1], edge_index=[2, 170], y=[200, 1], new_pos=[200, 4], y_mark=[200, 1], num_nodes=200, bond_length=[170, 1])

In [13]:
dataset[0].x

tensor([[ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 7],
        [ 7],
        [16],
        [16],
        [16],
        [16],
        [ 8],
        [ 8],
        [ 8],
        [ 8],
        [ 8],
        [ 8],
        [ 8],
        [ 8],
        [ 8],
      

tensor([[ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 3],
        [ 7],
        [ 7],
        [16],
        [16],
        [16],
        [16],
        [ 8],
        [ 8],
        [ 8],
        [ 8],
        [ 8],
        [ 8],
        [ 8],
        [ 8],
        [ 8],
      

In [14]:
dataset[0].edge_index

tensor([[ 56,  57,  57,  58,  58,  59,  59,  60,  60,  60,  61,  61,  61,  62,
          63,  64,  65,  67,  68,  69,  70,  72,  72,  73,  73,  74,  75,  76,
          77,  87,  97, 108, 115, 118, 123, 123, 123, 124, 124, 124, 125, 125,
         125, 125, 126, 126, 126, 126, 127, 127, 127, 127, 128, 128, 128, 128,
         129, 129, 129, 129, 130, 130, 130, 130, 131, 131, 132, 132, 132, 132,
         133, 133, 133, 133, 134, 134, 134, 135, 135, 135, 136, 136, 136, 137,
         137, 137, 138, 138, 138, 139, 139, 139, 140, 140, 140, 141, 141, 141,
         142, 142, 142, 143, 143, 143, 144, 144, 144, 145, 145, 145, 146, 146,
         147, 147, 148, 148, 148, 148, 149, 149, 150, 150, 151, 151, 152, 152,
         153, 153, 153, 153, 154, 154, 155, 155, 156, 157, 158, 159, 160, 161,
         162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175,
         178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
         193, 194],
        [ 59,  61,  58,  57, 136

tensor([[ 56,  57,  57,  58,  58,  59,  59,  60,  60,  60,  61,  61,  61,  62,
          63,  64,  65,  67,  68,  69,  70,  72,  72,  73,  73,  74,  75,  76,
          77,  87,  97, 108, 115, 118, 123, 123, 123, 124, 124, 124, 125, 125,
         125, 125, 126, 126, 126, 126, 127, 127, 127, 127, 128, 128, 128, 128,
         129, 129, 129, 129, 130, 130, 130, 130, 131, 131, 132, 132, 132, 132,
         133, 133, 133, 133, 134, 134, 134, 135, 135, 135, 136, 136, 136, 137,
         137, 137, 138, 138, 138, 139, 139, 139, 140, 140, 140, 141, 141, 141,
         142, 142, 142, 143, 143, 143, 144, 144, 144, 145, 145, 145, 146, 146,
         147, 147, 148, 148, 148, 148, 149, 149, 150, 150, 151, 151, 152, 152,
         153, 153, 153, 153, 154, 154, 155, 155, 156, 157, 158, 159, 160, 161,
         162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175,
         178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
         193, 194],
        [ 59,  61,  58,  57, 136

In [15]:
dataset[0].y

tensor([[0.4429],
        [0.4471],
        [0.4320],
        [0.4503],
        [0.4535],
        [0.4500],
        [0.4510],
        [0.4572],
        [0.4387],
        [0.4448],
        [0.4534],
        [0.4490],
        [0.4495],
        [0.4476],
        [0.4563],
        [0.4497],
        [0.4499],
        [0.4455],
        [0.4623],
        [0.4429],
        [0.4400],
        [0.4564],
        [0.4526],
        [0.4593],
        [0.4470],
        [0.4463],
        [0.4532],
        [0.4393],
        [0.4493],
        [0.4454],
        [0.4480],
        [0.4412],
        [0.4479],
        [0.4493],
        [0.4508],
        [0.4469],
        [0.4469],
        [0.4429],
        [0.4480],
        [0.4504],
        [0.4546],
        [0.4508],
        [0.4456],
        [0.4560],
        [0.4375],
        [0.4414],
        [0.4613],
        [0.4351],
        [0.4443],
        [0.4502],
        [0.4474],
        [0.4580],
        [0.4562],
        [0.4471],
        [0.4423],
        [0

tensor([[0.4429],
        [0.4471],
        [0.4320],
        [0.4503],
        [0.4535],
        [0.4500],
        [0.4510],
        [0.4572],
        [0.4387],
        [0.4448],
        [0.4534],
        [0.4490],
        [0.4495],
        [0.4476],
        [0.4563],
        [0.4497],
        [0.4499],
        [0.4455],
        [0.4623],
        [0.4429],
        [0.4400],
        [0.4564],
        [0.4526],
        [0.4593],
        [0.4470],
        [0.4463],
        [0.4532],
        [0.4393],
        [0.4493],
        [0.4454],
        [0.4480],
        [0.4412],
        [0.4479],
        [0.4493],
        [0.4508],
        [0.4469],
        [0.4469],
        [0.4429],
        [0.4480],
        [0.4504],
        [0.4546],
        [0.4508],
        [0.4456],
        [0.4560],
        [0.4375],
        [0.4414],
        [0.4613],
        [0.4351],
        [0.4443],
        [0.4502],
        [0.4474],
        [0.4580],
        [0.4562],
        [0.4471],
        [0.4423],
        [0

In [16]:
import torch
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

tensor([[0., 0.],
        [0., 0.]])